export const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const FORM_VALIDATION_ERROR = 'FORM_VALIDATION_ERROR'
export const CHECKOUT = 'CHECKOUT'
export const CHECKOUT_ERROR = 'CHECKOUT_ERROR'




